interface APIResponse {
	nextSave: {
		saved: boolean;
		lastSaved: number;
	};
	took: number;
	success: boolean;
	queried: number;
	uuid: string;
	player: string;
	statsVersion: 1 | 2 | 3 | 4;
	stats: {
		skywars_experience: number;
		coins: number;
		opals: number;
		heads: number;
		souls: number;
		kills: number;
		deaths: number;
		wins: number;
		losses: number;
		time_played: number;
		wins_solo: number;
		losses_solo: number;
		kills_solo: number;
		deaths_solo: number;
		time_played_solo: number;
		wins_team: number;
		losses_team: number;
		kills_team: number;
		deaths_team: number;
		time_played_team: number;
		wins_mini?: number;
		kills_mini?: number;
		time_played_mini?: number;
	};
	generic: {
		display: {
			levelFormattedWithBrackets: string;
			levelFormatted: string;
			newPackageRank: string;
			monthlyPackageRank: string;
			rankPlusColor: string;
			monthlyRankColor: string;
			skywarsActiveScheme: string;
			tagColor?: string;
			tag?: string;
		};
		stats: {
			karma: number;
			networkExp: number;
			firstLogin: number;
			lastLogin: number;
			achievementPoints: number;
			guild: string;
			guildRank: string;
			guildJoined: number;
		};
	};
	extendedStats: {
		activeKit_SOLO?: string;
		activeKit_TEAM?: string;
		activeKit_RANKED?: string;
		angel_of_death_level: number;
		angels_offering: number | null;
		survived_players: number;
		blocks_broken: number;
		blocks_placed: number;
		egg_thrown: number;
		enderpearls_thrown: number;
		souls_gathered: number;
		souls: number;
		opals: number;
		soul_well: number;
		paid_souls: number;
		assists: number;
		arrows_hit: number;
		arrows_shot: number;
		items_enchanted: number;
		chests_opened: number;
		melee_kills: number;
		void_kills: number;
		bow_kills: number;
		mob_kills: number;
		kitsMaxPrestige: number;
		time_played_solo: number;
		time_played_team: number;
		time_played_mega?: number;
		time_played_ranked?: number;
		time_played_lab?: number;
		time_played_mini?: number;
		heads_eww: number | null;
		heads_yucky: number | null;
		heads_meh: number | null;
		heads_decent: number | null;
		heads_salty: number | null;
		heads_tasty: number | null;
		heads_succulent: number | null;
		heads_divine: number | null;
		heads_heavenly: number | null;
		heads_ethereal: number | null;
		heads_indescribable: number | null;
		heads_special: number | null;
		heads_sweet: number | null;
		perkslot?: {
			normal?: {
				"1"?: string;
				"2"?: string;
				"3"?: string;
				"4"?: string;
				"5"?: string;
				"6"?: string;
				"7"?: string;
			};
			insane?: {
				"1"?: string;
				"2"?: string;
				"3"?: string;
				"4"?: string;
				"5"?: string;
				"6"?: string;
				"7"?: string;
			};
			mega?: {
				"1"?: string;
				"2"?: string;
				"3"?: string;
				"4"?: string;
				"5"?: string;
				"6"?: string;
				"7"?: string;
			};
		};
		SkyWars_skywars_rating_3_18_position: number | null;
		SkyWars_skywars_rating_3_18_rating: number | null;
		SkyWars_skywars_rating_4_18_position: number | null;
		SkyWars_skywars_rating_4_18_rating: number | null;
		SkyWars_skywars_rating_5_18_position: number | null;
		SkyWars_skywars_rating_5_18_rating: number | null;
		SkyWars_skywars_rating_6_18_position: number | null;
		SkyWars_skywars_rating_6_18_rating: number | null;
		SkyWars_skywars_rating_7_18_position: number | null;
		SkyWars_skywars_rating_7_18_rating: number | null;
		SkyWars_skywars_rating_8_18_position: number | null;
		SkyWars_skywars_rating_8_18_rating: number | null;
		SkyWars_skywars_rating_9_18_position: number | null;
		SkyWars_skywars_rating_9_18_rating: number | null;
		SkyWars_skywars_rating_10_18_position: number | null;
		SkyWars_skywars_rating_10_18_rating: number | null;
		SkyWars_skywars_rating_11_18_position: number | null;
		SkyWars_skywars_rating_11_18_rating: number | null;
		SkyWars_skywars_rating_12_18_position: number | null;
		SkyWars_skywars_rating_12_18_rating: number | null;
		SkyWars_skywars_rating_1_19_position: number | null;
		SkyWars_skywars_rating_1_19_rating: number | null;
		SkyWars_skywars_rating_2_19_position: number | null;
		SkyWars_skywars_rating_2_19_rating: number | null;
		SkyWars_skywars_rating_3_19_position: number | null;
		SkyWars_skywars_rating_3_19_rating: number | null;
		SkyWars_skywars_rating_4_19_position: number | null;
		SkyWars_skywars_rating_4_19_rating: number | null;
		SkyWars_skywars_rating_5_19_position: number | null;
		SkyWars_skywars_rating_5_19_rating: number | null;
		SkyWars_skywars_rating_6_19_position: number | null;
		SkyWars_skywars_rating_6_19_rating: number | null;
		SkyWars_skywars_rating_7_19_position: number | null;
		SkyWars_skywars_rating_7_19_rating: number | null;
		SkyWars_skywars_rating_8_19_position: number | null;
		SkyWars_skywars_rating_8_19_rating: number | null;
		SkyWars_skywars_rating_9_19_position: number | null;
		SkyWars_skywars_rating_9_19_rating: number | null;
		SkyWars_skywars_rating_10_19_position: number | null;
		SkyWars_skywars_rating_10_19_rating: number | null;
		SkyWars_skywars_rating_11_19_position: number | null;
		SkyWars_skywars_rating_11_19_rating: number | null;
		SkyWars_skywars_rating_12_19_position: number | null;
		SkyWars_skywars_rating_12_19_rating: number | null;
		SkyWars_skywars_rating_1_20_position: number | null;
		SkyWars_skywars_rating_1_20_rating: number | null;
		SkyWars_skywars_rating_2_20_position: number | null;
		SkyWars_skywars_rating_2_20_rating: number | null;
		SkyWars_skywars_rating_3_20_position: number | null;
		SkyWars_skywars_rating_3_20_rating: number | null;
		SkyWars_skywars_rating_4_20_position: number | null;
		SkyWars_skywars_rating_4_20_rating: number | null;
		SkyWars_skywars_rating_5_20_position: number | null;
		SkyWars_skywars_rating_5_20_rating: number | null;
		SkyWars_skywars_rating_6_20_position: number | null;
		SkyWars_skywars_rating_6_20_rating: number | null;
		SkyWars_skywars_rating_7_20_position: number | null;
		SkyWars_skywars_rating_7_20_rating: number | null;
		SkyWars_skywars_rating_8_20_position: number | null;
		SkyWars_skywars_rating_8_20_rating: number | null;
		SkyWars_skywars_rating_9_20_position: number | null;
		SkyWars_skywars_rating_9_20_rating: number | null;
		SkyWars_skywars_rating_10_20_position: number | null;
		SkyWars_skywars_rating_10_20_rating: number | null;
		SkyWars_skywars_rating_11_20_position: number | null;
		SkyWars_skywars_rating_11_20_rating: number | null;
		SkyWars_skywars_rating_12_20_position: number | null;
		SkyWars_skywars_rating_12_20_rating: number | null;
		SkyWars_skywars_rating_1_21_position: number | null;
		SkyWars_skywars_rating_1_21_rating: number | null;
		SkyWars_skywars_rating_2_21_position: number | null;
		SkyWars_skywars_rating_2_21_rating: number | null;
		SkyWars_skywars_rating_3_21_position: number | null;
		SkyWars_skywars_rating_3_21_rating: number | null;
		SkyWars_skywars_rating_4_21_position: number | null;
		SkyWars_skywars_rating_4_21_rating: number | null;
		SkyWars_skywars_rating_5_21_position: number | null;
		SkyWars_skywars_rating_5_21_rating: number | null;
		SkyWars_skywars_rating_6_21_position: number | null;
		SkyWars_skywars_rating_6_21_rating: number | null;
		SkyWars_skywars_rating_7_21_position: number | null;
		SkyWars_skywars_rating_7_21_rating: number | null;
		SkyWars_skywars_rating_8_21_position: number | null;
		SkyWars_skywars_rating_8_21_rating: number | null;
		SkyWars_skywars_rating_9_21_position: number | null;
		SkyWars_skywars_rating_9_21_rating: number | null;
		SkyWars_skywars_rating_10_21_position: number | null;
		SkyWars_skywars_rating_10_21_rating: number | null;
		SkyWars_skywars_rating_11_21_position: number | null;
		SkyWars_skywars_rating_11_21_rating: number | null;
		SkyWars_skywars_rating_12_21_position: number | null;
		SkyWars_skywars_rating_12_21_rating: number | null;
		SkyWars_skywars_rating_1_22_position: number | null;
		SkyWars_skywars_rating_1_22_rating: number | null;
		SkyWars_skywars_rating_2_22_position: number | null;
		SkyWars_skywars_rating_2_22_rating: number | null;
		SkyWars_skywars_rating_3_22_position: number | null;
		SkyWars_skywars_rating_3_22_rating: number | null;
		SkyWars_skywars_rating_4_22_position: number | null;
		SkyWars_skywars_rating_4_22_rating: number | null;
		SkyWars_skywars_rating_5_22_position: number | null;
		SkyWars_skywars_rating_5_22_rating: number | null;
		SkyWars_skywars_rating_6_22_position: number | null;
		SkyWars_skywars_rating_6_22_rating: number | null;
		SkyWars_skywars_rating_7_22_position: number | null;
		SkyWars_skywars_rating_7_22_rating: number | null;
		SkyWars_skywars_rating_8_22_position: number | null;
		SkyWars_skywars_rating_8_22_rating: number | null;
		SkyWars_skywars_rating_9_22_position: number | null;
		SkyWars_skywars_rating_9_22_rating: number | null;
		SkyWars_skywars_rating_10_22_position: number | null;
		SkyWars_skywars_rating_10_22_rating: number | null;
		SkyWars_skywars_rating_11_22_position: number | null;
		SkyWars_skywars_rating_11_22_rating: number | null;
		SkyWars_skywars_rating_12_22_position: number | null;
		SkyWars_skywars_rating_12_22_rating: number | null;
	};
	kitStats: {
		wins_kit_advanced_solo_armorer: number | null;
		losses_kit_advanced_solo_armorer: number | null;
		kills_kit_advanced_solo_armorer: number | null;
		deaths_kit_advanced_solo_armorer: number | null;
		time_played_kit_advanced_solo_armorer: number | null;
		xp_kit_advanced_solo_armorer: number | null;
		wins_kit_basic_solo_archeologist: number | null;
		losses_kit_basic_solo_archeologist: number | null;
		kills_kit_basic_solo_archeologist: number | null;
		deaths_kit_basic_solo_archeologist: number | null;
		time_played_kit_basic_solo_archeologist: number | null;
		xp_kit_basic_solo_archeologist: number | null;
		wins_kit_basic_solo_armorsmith: number | null;
		losses_kit_basic_solo_armorsmith: number | null;
		kills_kit_basic_solo_armorsmith: number | null;
		deaths_kit_basic_solo_armorsmith: number | null;
		time_played_kit_basic_solo_armorsmith: number | null;
		xp_kit_basic_solo_armorsmith: number | null;
		"wins_kit_basic_solo_baseball-player": number | null;
		"losses_kit_basic_solo_baseball-player": number | null;
		"kills_kit_basic_solo_baseball-player": number | null;
		"deaths_kit_basic_solo_baseball-player": number | null;
		"time_played_kit_basic_solo_baseball-player": number | null;
		"xp_kit_basic_solo_baseball-player": number | null;
		wins_kit_basic_solo_batguy: number | null;
		losses_kit_basic_solo_batguy: number | null;
		kills_kit_basic_solo_batguy: number | null;
		deaths_kit_basic_solo_batguy: number | null;
		time_played_kit_basic_solo_batguy: number | null;
		xp_kit_basic_solo_batguy: number | null;
		wins_kit_basic_solo_cactus: number | null;
		losses_kit_basic_solo_cactus: number | null;
		kills_kit_basic_solo_cactus: number | null;
		deaths_kit_basic_solo_cactus: number | null;
		time_played_kit_basic_solo_cactus: number | null;
		xp_kit_basic_solo_cactus: number | null;
		wins_kit_advanced_solo_cannoneer: number | null;
		losses_kit_advanced_solo_cannoneer: number | null;
		kills_kit_advanced_solo_cannoneer: number | null;
		deaths_kit_advanced_solo_cannoneer: number | null;
		time_played_kit_advanced_solo_cannoneer: number | null;
		xp_kit_advanced_solo_cannoneer: number | null;
		wins_kit_basic_solo_default: number | null;
		losses_kit_basic_solo_default: number | null;
		kills_kit_basic_solo_default: number | null;
		deaths_kit_basic_solo_default: number | null;
		time_played_kit_basic_solo_default: number | null;
		xp_kit_basic_solo_default: number | null;
		wins_kit_basic_solo_disco: number | null;
		losses_kit_basic_solo_disco: number | null;
		kills_kit_basic_solo_disco: number | null;
		deaths_kit_basic_solo_disco: number | null;
		time_played_kit_basic_solo_disco: number | null;
		xp_kit_basic_solo_disco: number | null;
		wins_kit_basic_solo_ecologist: number | null;
		losses_kit_basic_solo_ecologist: number | null;
		kills_kit_basic_solo_ecologist: number | null;
		deaths_kit_basic_solo_ecologist: number | null;
		time_played_kit_basic_solo_ecologist: number | null;
		xp_kit_basic_solo_ecologist: number | null;
		wins_kit_advanced_solo_enchanter: number | null;
		losses_kit_advanced_solo_enchanter: number | null;
		kills_kit_advanced_solo_enchanter: number | null;
		deaths_kit_advanced_solo_enchanter: number | null;
		time_played_kit_advanced_solo_enchanter: number | null;
		xp_kit_advanced_solo_enchanter: number | null;
		wins_kit_enderchest_solo_enderchest: number | null;
		losses_kit_enderchest_solo_enderchest: number | null;
		kills_kit_enderchest_solo_enderchest: number | null;
		deaths_kit_enderchest_solo_enderchest: number | null;
		time_played_kit_enderchest_solo_enderchest: number | null;
		xp_kit_enderchest_solo_enderchest: number | null;
		wins_kit_advanced_solo_enderman: number | null;
		losses_kit_advanced_solo_enderman: number | null;
		kills_kit_advanced_solo_enderman: number | null;
		deaths_kit_advanced_solo_enderman: number | null;
		time_played_kit_advanced_solo_enderman: number | null;
		xp_kit_advanced_solo_enderman: number | null;
		wins_kit_basic_solo_energix: number | null;
		losses_kit_basic_solo_energix: number | null;
		kills_kit_basic_solo_energix: number | null;
		deaths_kit_basic_solo_energix: number | null;
		time_played_kit_basic_solo_energix: number | null;
		xp_kit_basic_solo_energix: number | null;
		wins_kit_advanced_solo_farmer: number | null;
		losses_kit_advanced_solo_farmer: number | null;
		kills_kit_advanced_solo_farmer: number | null;
		deaths_kit_advanced_solo_farmer: number | null;
		time_played_kit_advanced_solo_farmer: number | null;
		xp_kit_advanced_solo_farmer: number | null;
		wins_kit_basic_solo_fisherman: number | null;
		losses_kit_basic_solo_fisherman: number | null;
		kills_kit_basic_solo_fisherman: number | null;
		deaths_kit_basic_solo_fisherman: number | null;
		time_played_kit_basic_solo_fisherman: number | null;
		xp_kit_basic_solo_fisherman: number | null;
		wins_kit_basic_solo_frog: number | null;
		losses_kit_basic_solo_frog: number | null;
		kills_kit_basic_solo_frog: number | null;
		deaths_kit_basic_solo_frog: number | null;
		time_played_kit_basic_solo_frog: number | null;
		xp_kit_basic_solo_frog: number | null;
		wins_kit_basic_solo_grenade: number | null;
		losses_kit_basic_solo_grenade: number | null;
		kills_kit_basic_solo_grenade: number | null;
		deaths_kit_basic_solo_grenade: number | null;
		time_played_kit_basic_solo_grenade: number | null;
		xp_kit_basic_solo_grenade: number | null;
		wins_kit_advanced_solo_guardian: number | null;
		losses_kit_advanced_solo_guardian: number | null;
		kills_kit_advanced_solo_guardian: number | null;
		deaths_kit_advanced_solo_guardian: number | null;
		time_played_kit_advanced_solo_guardian: number | null;
		xp_kit_advanced_solo_guardian: number | null;
		wins_kit_basic_solo_healer: number | null;
		losses_kit_basic_solo_healer: number | null;
		kills_kit_basic_solo_healer: number | null;
		deaths_kit_basic_solo_healer: number | null;
		time_played_kit_basic_solo_healer: number | null;
		xp_kit_basic_solo_healer: number | null;
		wins_kit_advanced_solo_hunter: number | null;
		losses_kit_advanced_solo_hunter: number | null;
		kills_kit_advanced_solo_hunter: number | null;
		deaths_kit_advanced_solo_hunter: number | null;
		time_played_kit_advanced_solo_hunter: number | null;
		xp_kit_advanced_solo_hunter: number | null;
		wins_kit_advanced_solo_jester: number | null;
		losses_kit_advanced_solo_jester: number | null;
		kills_kit_advanced_solo_jester: number | null;
		deaths_kit_advanced_solo_jester: number | null;
		time_played_kit_advanced_solo_jester: number | null;
		xp_kit_advanced_solo_jester: number | null;
		wins_kit_advanced_solo_knight: number | null;
		losses_kit_advanced_solo_knight: number | null;
		kills_kit_advanced_solo_knight: number | null;
		deaths_kit_advanced_solo_knight: number | null;
		time_played_kit_advanced_solo_knight: number | null;
		xp_kit_advanced_solo_knight: number | null;
		wins_kit_advanced_solo_magician: number | null;
		losses_kit_advanced_solo_magician: number | null;
		kills_kit_advanced_solo_magician: number | null;
		deaths_kit_advanced_solo_magician: number | null;
		time_played_kit_advanced_solo_magician: number | null;
		xp_kit_advanced_solo_magician: number | null;
		wins_kit_basic_solo_pharaoh: number | null;
		losses_kit_basic_solo_pharaoh: number | null;
		kills_kit_basic_solo_pharaoh: number | null;
		deaths_kit_basic_solo_pharaoh: number | null;
		time_played_kit_basic_solo_pharaoh: number | null;
		xp_kit_basic_solo_pharaoh: number | null;
		"wins_kit_advanced_solo_pig-rider": number | null;
		"losses_kit_advanced_solo_pig-rider": number | null;
		"kills_kit_advanced_solo_pig-rider": number | null;
		"deaths_kit_advanced_solo_pig-rider": number | null;
		"time_played_kit_advanced_solo_pig-rider": number | null;
		"xp_kit_advanced_solo_pig-rider": number | null;
		wins_kit_advanced_solo_pyro: number | null;
		losses_kit_advanced_solo_pyro: number | null;
		kills_kit_advanced_solo_pyro: number | null;
		deaths_kit_advanced_solo_pyro: number | null;
		time_played_kit_advanced_solo_pyro: number | null;
		xp_kit_advanced_solo_pyro: number | null;
		wins_kit_basic_solo_princess: number | null;
		losses_kit_basic_solo_princess: number | null;
		kills_kit_basic_solo_princess: number | null;
		deaths_kit_basic_solo_princess: number | null;
		time_played_kit_basic_solo_princess: number | null;
		xp_kit_basic_solo_princess: number | null;
		wins_kit_basic_solo_rookie: number | null;
		losses_kit_basic_solo_rookie: number | null;
		kills_kit_basic_solo_rookie: number | null;
		deaths_kit_basic_solo_rookie: number | null;
		time_played_kit_basic_solo_rookie: number | null;
		xp_kit_basic_solo_rookie: number | null;
		wins_kit_advanced_solo_salmon: number | null;
		losses_kit_advanced_solo_salmon: number | null;
		kills_kit_advanced_solo_salmon: number | null;
		deaths_kit_advanced_solo_salmon: number | null;
		time_played_kit_advanced_solo_salmon: number | null;
		xp_kit_advanced_solo_salmon: number | null;
		wins_kit_basic_solo_scout: number | null;
		losses_kit_basic_solo_scout: number | null;
		kills_kit_basic_solo_scout: number | null;
		deaths_kit_basic_solo_scout: number | null;
		time_played_kit_basic_solo_scout: number | null;
		xp_kit_basic_solo_scout: number | null;
		wins_kit_advanced_solo_slime: number | null;
		losses_kit_advanced_solo_slime: number | null;
		kills_kit_advanced_solo_slime: number | null;
		deaths_kit_advanced_solo_slime: number | null;
		time_played_kit_advanced_solo_slime: number | null;
		xp_kit_advanced_solo_slime: number | null;
		wins_kit_advanced_solo_sloth: number | null;
		losses_kit_advanced_solo_sloth: number | null;
		kills_kit_advanced_solo_sloth: number | null;
		deaths_kit_advanced_solo_sloth: number | null;
		time_played_kit_advanced_solo_sloth: number | null;
		xp_kit_advanced_solo_sloth: number | null;
		wins_kit_basic_solo_snowman: number | null;
		losses_kit_basic_solo_snowman: number | null;
		kills_kit_basic_solo_snowman: number | null;
		deaths_kit_basic_solo_snowman: number | null;
		time_played_kit_basic_solo_snowman: number | null;
		xp_kit_basic_solo_snowman: number | null;
		wins_kit_basic_solo_speleologist: number | null;
		losses_kit_basic_solo_speleologist: number | null;
		kills_kit_basic_solo_speleologist: number | null;
		deaths_kit_basic_solo_speleologist: number | null;
		time_played_kit_basic_solo_speleologist: number | null;
		xp_kit_basic_solo_speleologist: number | null;
		wins_kit_basic_solo_troll: number | null;
		losses_kit_basic_solo_troll: number | null;
		kills_kit_basic_solo_troll: number | null;
		deaths_kit_basic_solo_troll: number | null;
		time_played_kit_basic_solo_troll: number | null;
		xp_kit_basic_solo_troll: number | null;
		wins_kit_basic_solo_warlock: number | null;
		losses_kit_basic_solo_warlock: number | null;
		kills_kit_basic_solo_warlock: number | null;
		deaths_kit_basic_solo_warlock: number | null;
		time_played_kit_basic_solo_warlock: number | null;
		xp_kit_basic_solo_warlock: number | null;
		wins_kit_advanced_solo_zookeeper: number | null;
		losses_kit_advanced_solo_zookeeper: number | null;
		kills_kit_advanced_solo_zookeeper: number | null;
		deaths_kit_advanced_solo_zookeeper: number | null;
		time_played_kit_advanced_solo_zookeeper: number | null;
		xp_kit_advanced_solo_zookeeper: number | null;
		"wins_kit_basic_solo_fallen-angel": number | null;
		"losses_kit_basic_solo_fallen-angel": number | null;
		"kills_kit_basic_solo_fallen-angel": number | null;
		"deaths_kit_basic_solo_fallen-angel": number | null;
		"time_played_kit_basic_solo_fallen-angel": number | null;
		"xp_kit_basic_solo_fallen-angel": number | null;
		wins_kit_advanced_solo_engineer: number | null;
		losses_kit_advanced_solo_engineer: number | null;
		kills_kit_advanced_solo_engineer: number | null;
		deaths_kit_advanced_solo_engineer: number | null;
		time_played_kit_advanced_solo_engineer: number | null;
		xp_kit_advanced_solo_engineer: number | null;
		wins_kit_defending_team_armorer: number | null;
		losses_kit_defending_team_armorer: number | null;
		kills_kit_defending_team_armorer: number | null;
		deaths_kit_defending_team_armorer: number | null;
		time_played_kit_defending_team_armorer: number | null;
		xp_kit_defending_team_armorer: number | null;
		wins_kit_attacking_team_archeologist: number | null;
		losses_kit_attacking_team_archeologist: number | null;
		kills_kit_attacking_team_archeologist: number | null;
		deaths_kit_attacking_team_archeologist: number | null;
		time_played_kit_attacking_team_archeologist: number | null;
		xp_kit_attacking_team_archeologist: number | null;
		wins_kit_supporting_team_armorsmith: number | null;
		losses_kit_supporting_team_armorsmith: number | null;
		kills_kit_supporting_team_armorsmith: number | null;
		deaths_kit_supporting_team_armorsmith: number | null;
		time_played_kit_supporting_team_armorsmith: number | null;
		xp_kit_supporting_team_armorsmith: number | null;
		"wins_kit_defending_team_baseball-player": number | null;
		"losses_kit_defending_team_baseball-player": number | null;
		"kills_kit_defending_team_baseball-player": number | null;
		"deaths_kit_defending_team_baseball-player": number | null;
		"time_played_kit_defending_team_baseball-player": number | null;
		"xp_kit_defending_team_baseball-player": number | null;
		wins_kit_defending_team_batguy: number | null;
		losses_kit_defending_team_batguy: number | null;
		kills_kit_defending_team_batguy: number | null;
		deaths_kit_defending_team_batguy: number | null;
		time_played_kit_defending_team_batguy: number | null;
		xp_kit_defending_team_batguy: number | null;
		wins_kit_defending_team_cactus: number | null;
		losses_kit_defending_team_cactus: number | null;
		kills_kit_defending_team_cactus: number | null;
		deaths_kit_defending_team_cactus: number | null;
		time_played_kit_defending_team_cactus: number | null;
		xp_kit_defending_team_cactus: number | null;
		wins_kit_mining_team_cannoneer: number | null;
		losses_kit_mining_team_cannoneer: number | null;
		kills_kit_mining_team_cannoneer: number | null;
		deaths_kit_mining_team_cannoneer: number | null;
		time_played_kit_mining_team_cannoneer: number | null;
		xp_kit_mining_team_cannoneer: number | null;
		wins_kit_mining_team_default: number | null;
		losses_kit_mining_team_default: number | null;
		kills_kit_mining_team_default: number | null;
		deaths_kit_mining_team_default: number | null;
		time_played_kit_mining_team_default: number | null;
		xp_kit_mining_team_default: number | null;
		wins_kit_defending_team_disco: number | null;
		losses_kit_defending_team_disco: number | null;
		kills_kit_defending_team_disco: number | null;
		deaths_kit_defending_team_disco: number | null;
		time_played_kit_defending_team_disco: number | null;
		xp_kit_defending_team_disco: number | null;
		wins_kit_supporting_team_ecologist: number | null;
		losses_kit_supporting_team_ecologist: number | null;
		kills_kit_supporting_team_ecologist: number | null;
		deaths_kit_supporting_team_ecologist: number | null;
		time_played_kit_supporting_team_ecologist: number | null;
		xp_kit_supporting_team_ecologist: number | null;
		wins_kit_supporting_team_enchanter: number | null;
		losses_kit_supporting_team_enchanter: number | null;
		kills_kit_supporting_team_enchanter: number | null;
		deaths_kit_supporting_team_enchanter: number | null;
		time_played_kit_supporting_team_enchanter: number | null;
		xp_kit_supporting_team_enchanter: number | null;
		wins_kit_enderchest_team_enderchest: number | null;
		losses_kit_enderchest_team_enderchest: number | null;
		kills_kit_enderchest_team_enderchest: number | null;
		deaths_kit_enderchest_team_enderchest: number | null;
		time_played_kit_enderchest_team_enderchest: number | null;
		xp_kit_enderchest_team_enderchest: number | null;
		wins_kit_attacking_team_enderman: number | null;
		losses_kit_attacking_team_enderman: number | null;
		kills_kit_attacking_team_enderman: number | null;
		deaths_kit_attacking_team_enderman: number | null;
		time_played_kit_attacking_team_enderman: number | null;
		xp_kit_attacking_team_enderman: number | null;
		wins_kit_attacking_team_energix: number | null;
		losses_kit_attacking_team_energix: number | null;
		kills_kit_attacking_team_energix: number | null;
		deaths_kit_attacking_team_energix: number | null;
		time_played_kit_attacking_team_energix: number | null;
		xp_kit_attacking_team_energix: number | null;
		wins_kit_defending_team_farmer: number | null;
		losses_kit_defending_team_farmer: number | null;
		kills_kit_defending_team_farmer: number | null;
		deaths_kit_defending_team_farmer: number | null;
		time_played_kit_defending_team_farmer: number | null;
		xp_kit_defending_team_farmer: number | null;
		wins_kit_attacking_team_fisherman: number | null;
		losses_kit_attacking_team_fisherman: number | null;
		kills_kit_attacking_team_fisherman: number | null;
		deaths_kit_attacking_team_fisherman: number | null;
		time_played_kit_attacking_team_fisherman: number | null;
		xp_kit_attacking_team_fisherman: number | null;
		wins_kit_defending_team_frog: number | null;
		losses_kit_defending_team_frog: number | null;
		kills_kit_defending_team_frog: number | null;
		deaths_kit_defending_team_frog: number | null;
		time_played_kit_defending_team_frog: number | null;
		xp_kit_defending_team_frog: number | null;
		wins_kit_attacking_team_grenade: number | null;
		losses_kit_attacking_team_grenade: number | null;
		kills_kit_attacking_team_grenade: number | null;
		deaths_kit_attacking_team_grenade: number | null;
		time_played_kit_attacking_team_grenade: number | null;
		xp_kit_attacking_team_grenade: number | null;
		wins_kit_defending_team_golem: number | null;
		losses_kit_defending_team_golem: number | null;
		kills_kit_defending_team_golem: number | null;
		deaths_kit_defending_team_golem: number | null;
		time_played_kit_defending_team_golem: number | null;
		xp_kit_defending_team_golem: number | null;
		wins_kit_defending_team_guardian: number | null;
		losses_kit_defending_team_guardian: number | null;
		kills_kit_defending_team_guardian: number | null;
		deaths_kit_defending_team_guardian: number | null;
		time_played_kit_defending_team_guardian: number | null;
		xp_kit_defending_team_guardian: number | null;
		wins_kit_supporting_team_healer: number | null;
		losses_kit_supporting_team_healer: number | null;
		kills_kit_supporting_team_healer: number | null;
		deaths_kit_supporting_team_healer: number | null;
		time_played_kit_supporting_team_healer: number | null;
		xp_kit_supporting_team_healer: number | null;
		wins_kit_attacking_team_hunter: number | null;
		losses_kit_attacking_team_hunter: number | null;
		kills_kit_attacking_team_hunter: number | null;
		deaths_kit_attacking_team_hunter: number | null;
		time_played_kit_attacking_team_hunter: number | null;
		xp_kit_attacking_team_hunter: number | null;
		wins_kit_attacking_team_jester: number | null;
		losses_kit_attacking_team_jester: number | null;
		kills_kit_attacking_team_jester: number | null;
		deaths_kit_attacking_team_jester: number | null;
		time_played_kit_attacking_team_jester: number | null;
		xp_kit_attacking_team_jester: number | null;
		wins_kit_attacking_team_knight: number | null;
		losses_kit_attacking_team_knight: number | null;
		kills_kit_attacking_team_knight: number | null;
		deaths_kit_attacking_team_knight: number | null;
		time_played_kit_attacking_team_knight: number | null;
		xp_kit_attacking_team_knight: number | null;
		wins_kit_supporting_team_pharaoh: number | null;
		losses_kit_supporting_team_pharaoh: number | null;
		kills_kit_supporting_team_pharaoh: number | null;
		deaths_kit_supporting_team_pharaoh: number | null;
		time_played_kit_supporting_team_pharaoh: number | null;
		xp_kit_supporting_team_pharaoh: number | null;
		"wins_kit_attacking_team_pig-rider": number | null;
		"losses_kit_attacking_team_pig-rider": number | null;
		"kills_kit_attacking_team_pig-rider": number | null;
		"deaths_kit_attacking_team_pig-rider": number | null;
		"time_played_kit_attacking_team_pig-rider": number | null;
		"xp_kit_attacking_team_pig-rider": number | null;
		wins_kit_supporting_team_pyro: number | null;
		losses_kit_supporting_team_pyro: number | null;
		kills_kit_supporting_team_pyro: number | null;
		deaths_kit_supporting_team_pyro: number | null;
		time_played_kit_supporting_team_pyro: number | null;
		xp_kit_supporting_team_pyro: number | null;
		wins_kit_supporting_team_princess: number | null;
		losses_kit_supporting_team_princess: number | null;
		kills_kit_supporting_team_princess: number | null;
		deaths_kit_supporting_team_princess: number | null;
		time_played_kit_supporting_team_princess: number | null;
		xp_kit_supporting_team_princess: number | null;
		wins_kit_supporting_team_rookie: number | null;
		losses_kit_supporting_team_rookie: number | null;
		kills_kit_supporting_team_rookie: number | null;
		deaths_kit_supporting_team_rookie: number | null;
		time_played_kit_supporting_team_rookie: number | null;
		xp_kit_supporting_team_rookie: number | null;
		wins_kit_attacking_team_salmon: number | null;
		losses_kit_attacking_team_salmon: number | null;
		kills_kit_attacking_team_salmon: number | null;
		deaths_kit_attacking_team_salmon: number | null;
		time_played_kit_attacking_team_salmon: number | null;
		xp_kit_attacking_team_salmon: number | null;
		wins_kit_attacking_team_scout: number | null;
		losses_kit_attacking_team_scout: number | null;
		kills_kit_attacking_team_scout: number | null;
		deaths_kit_attacking_team_scout: number | null;
		time_played_kit_attacking_team_scout: number | null;
		xp_kit_attacking_team_scout: number | null;
		wins_kit_attacking_team_slime: number | null;
		losses_kit_attacking_team_slime: number | null;
		kills_kit_attacking_team_slime: number | null;
		deaths_kit_attacking_team_slime: number | null;
		time_played_kit_attacking_team_slime: number | null;
		xp_kit_attacking_team_slime: number | null;
		wins_kit_attacking_team_sloth: number | null;
		losses_kit_attacking_team_sloth: number | null;
		kills_kit_attacking_team_sloth: number | null;
		deaths_kit_attacking_team_sloth: number | null;
		time_played_kit_attacking_team_sloth: number | null;
		xp_kit_attacking_team_sloth: number | null;
		wins_kit_attacking_team_snowman: number | null;
		losses_kit_attacking_team_snowman: number | null;
		kills_kit_attacking_team_snowman: number | null;
		deaths_kit_attacking_team_snowman: number | null;
		time_played_kit_attacking_team_snowman: number | null;
		xp_kit_attacking_team_snowman: number | null;
		wins_kit_mining_team_speleologist: number | null;
		losses_kit_mining_team_speleologist: number | null;
		kills_kit_mining_team_speleologist: number | null;
		deaths_kit_mining_team_speleologist: number | null;
		time_played_kit_mining_team_speleologist: number | null;
		xp_kit_mining_team_speleologist: number | null;
		wins_kit_supporting_team_troll: number | null;
		losses_kit_supporting_team_troll: number | null;
		kills_kit_supporting_team_troll: number | null;
		deaths_kit_supporting_team_troll: number | null;
		time_played_kit_supporting_team_troll: number | null;
		xp_kit_supporting_team_troll: number | null;
		wins_kit_supporting_team_warlock: number | null;
		losses_kit_supporting_team_warlock: number | null;
		kills_kit_supporting_team_warlock: number | null;
		deaths_kit_supporting_team_warlock: number | null;
		time_played_kit_supporting_team_warlock: number | null;
		xp_kit_supporting_team_warlock: number | null;
		wins_kit_supporting_team_zookeeper: number | null;
		losses_kit_supporting_team_zookeeper: number | null;
		kills_kit_supporting_team_zookeeper: number | null;
		deaths_kit_supporting_team_zookeeper: number | null;
		time_played_kit_supporting_team_zookeeper: number | null;
		xp_kit_supporting_team_zookeeper: number | null;
		"wins_kit_attacking_team_fallen-angel": number | null;
		"losses_kit_attacking_team_fallen-angel": number | null;
		"kills_kit_attacking_team_fallen-angel": number | null;
		"deaths_kit_attacking_team_fallen-angel": number | null;
		"time_played_kit_attacking_team_fallen-angel": number | null;
		"xp_kit_attacking_team_fallen-angel": number | null;
		"wins_kit_mythical_end-lord": number | null;
		"losses_kit_mythical_end-lord": number | null;
		"kills_kit_mythical_end-lord": number | null;
		"deaths_kit_mythical_end-lord": number | null;
		"time_played_kit_mythical_end-lord": number | null;
		"xp_kit_mythical_end-lord": number | null;
		wins_kit_mythical_thundermeister: number | null;
		losses_kit_mythical_thundermeister: number | null;
		kills_kit_mythical_thundermeister: number | null;
		deaths_kit_mythical_thundermeister: number | null;
		time_played_kit_mythical_thundermeister: number | null;
		xp_kit_mythical_thundermeister: number | null;
		wins_kit_mythical_cryomancer: number | null;
		losses_kit_mythical_cryomancer: number | null;
		kills_kit_mythical_cryomancer: number | null;
		deaths_kit_mythical_cryomancer: number | null;
		time_played_kit_mythical_cryomancer: number | null;
		xp_kit_mythical_cryomancer: number | null;
		wins_kit_mythical_fishmonger: number | null;
		losses_kit_mythical_fishmonger: number | null;
		kills_kit_mythical_fishmonger: number | null;
		deaths_kit_mythical_fishmonger: number | null;
		time_played_kit_mythical_fishmonger: number | null;
		xp_kit_mythical_fishmonger: number | null;
		wins_kit_mythical_chronobreaker: number | null;
		losses_kit_mythical_chronobreaker: number | null;
		kills_kit_mythical_chronobreaker: number | null;
		deaths_kit_mythical_chronobreaker: number | null;
		time_played_kit_mythical_chronobreaker: number | null;
		xp_kit_mythical_chronobreaker: number | null;
		"wins_kit_mythical_monster-trainer": number | null;
		"losses_kit_mythical_monster-trainer": number | null;
		"kills_kit_mythical_monster-trainer": number | null;
		"deaths_kit_mythical_monster-trainer": number | null;
		"time_played_kit_mythical_monster-trainer": number | null;
		"xp_kit_mythical_monster-trainer": number | null;
		"wins_kit_mythical_nether-lord": number | null;
		"losses_kit_mythical_nether-lord": number | null;
		"kills_kit_mythical_nether-lord": number | null;
		"deaths_kit_mythical_nether-lord": number | null;
		"time_played_kit_mythical_nether-lord": number | null;
		"xp_kit_mythical_nether-lord": number | null;
		wins_kit_mini_solo_armorer: number | null;
		losses_kit_mini_solo_armorer: number | null;
		kills_kit_mini_solo_armorer: number | null;
		deaths_kit_mini_solo_armorer: number | null;
		time_played_kit_mini_solo_armorer: number | null;
		xp_kit_mini_solo_armorer: number | null;
		wins_kit_mini_solo_athlete: number | null;
		losses_kit_mini_solo_athlete: number | null;
		kills_kit_mini_solo_athlete: number | null;
		deaths_kit_mini_solo_athlete: number | null;
		time_played_kit_mini_solo_athlete: number | null;
		xp_kit_mini_solo_athlete: number | null;
		wins_kit_mini_solo_blacksmith: number | null;
		losses_kit_mini_solo_blacksmith: number | null;
		kills_kit_mini_solo_blacksmith: number | null;
		deaths_kit_mini_solo_blacksmith: number | null;
		time_played_kit_mini_solo_blacksmith: number | null;
		xp_kit_mini_solo_blacksmith: number | null;
		wins_kit_mini_solo_bowman: number | null;
		losses_kit_mini_solo_bowman: number | null;
		kills_kit_mini_solo_bowman: number | null;
		deaths_kit_mini_solo_bowman: number | null;
		time_played_kit_mini_solo_bowman: number | null;
		xp_kit_mini_solo_bowman: number | null;
		wins_kit_mini_solo_champion: number | null;
		losses_kit_mini_solo_champion: number | null;
		kills_kit_mini_solo_champion: number | null;
		deaths_kit_mini_solo_champion: number | null;
		time_played_kit_mini_solo_champion: number | null;
		xp_kit_mini_solo_champion: number | null;
		wins_kit_mini_solo_healer: number | null;
		losses_kit_mini_solo_healer: number | null;
		kills_kit_mini_solo_healer: number | null;
		deaths_kit_mini_solo_healer: number | null;
		time_played_kit_mini_solo_healer: number | null;
		xp_kit_mini_solo_healer: number | null;
		wins_kit_mini_solo_hound: number | null;
		losses_kit_mini_solo_hound: number | null;
		kills_kit_mini_solo_hound: number | null;
		deaths_kit_mini_solo_hound: number | null;
		time_played_kit_mini_solo_hound: number | null;
		xp_kit_mini_solo_hound: number | null;
		wins_kit_mini_solo_magician: number | null;
		losses_kit_mini_solo_magician: number | null;
		kills_kit_mini_solo_magician: number | null;
		deaths_kit_mini_solo_magician: number | null;
		time_played_kit_mini_solo_magician: number | null;
		xp_kit_mini_solo_magician: number | null;
		wins_kit_mini_solo_paladin: number | null;
		losses_kit_mini_solo_paladin: number | null;
		kills_kit_mini_solo_paladin: number | null;
		deaths_kit_mini_solo_paladin: number | null;
		time_played_kit_mini_solo_paladin: number | null;
		xp_kit_mini_solo_paladin: number | null;
		wins_kit_mini_solo_pyromancer: number | null;
		losses_kit_mini_solo_pyromancer: number | null;
		kills_kit_mini_solo_pyromancer: number | null;
		deaths_kit_mini_solo_pyromancer: number | null;
		time_played_kit_mini_solo_pyromancer: number | null;
		xp_kit_mini_solo_pyromancer: number | null;
		wins_kit_mini_solo_scout: number | null;
		losses_kit_mini_solo_scout: number | null;
		kills_kit_mini_solo_scout: number | null;
		deaths_kit_mini_solo_scout: number | null;
		time_played_kit_mini_solo_scout: number | null;
		xp_kit_mini_solo_scout: number | null;
	};
	descentStats: {
		avarice?: number;
		projectiletrail_kings: boolean;
		grand_slam?: number;
		tenacity?: number;
		shard_seeker?: number;
		emblem_sigma_icon: boolean;
		meticulous_miner?: number;
		hide_and_seek?: number;
		killeffect_vaporized: boolean;
		midas_gift?: number;
		angels_offering?: number;
		killmessages_flex: boolean;
		first_blood?: number;
		fortune_teller?: number;
		fireproof?: number;
		cage_piston: boolean;
		corrupted_coinage?: number;
		librarian?: number;
		luckier_charm?: number;
		apothecary?: number;
		victorydance_super_sheep: boolean;
		cloak_falling_angel: boolean;
		killeffect_purple_tornado: boolean;
		sorcerers_spell?: number;
		fruit_finder?: number;
		ender_end_game?: number;
		smarty_pants?: number;
		killmessages_rainbow: boolean;
		diamond_in_the_rough?: number;
		telekinesis?: number;
		cage_balancing_act: boolean;
		distillery_discount?: number;
		archeologist_kit_opal: boolean;
		opalsmith?: number;
		double_edged_sword?: number;
		quest_masters_friend?: number;
		balloon_dual_dragon: boolean;
		deathcry_eponymous_dragon: boolean;
		kill_xp_boost?: number;
		perk_slot?: number;
		projectiletrail_descent_dragon: boolean;
		emblem_delta_icon: boolean;
		victorydance_double_dragons_descent: boolean;
		cloak_angels_prestige: boolean;
		scheme_demigod: boolean;
		fallen_angel_kit: boolean;
		xezbeth_luck?: number;
		harvesting_season?: number;
		favor_of_the_angel: boolean;
	};
}
